### PR TITLE
Add LDAP authentication backend

### PR DESCRIPTION
**Pull request by nebulade**
Hi,

not sure if this is useful for you, I have added a LDAP auth backend, which was quite straightforwards, given your nice layout of the functionality. The defaults work with https://github.com/nebulade/ldapjstestserver
The reason I have added it, is because I am looking into writing a Cloudron app.

Thanks for the great work,
Johannes

### CODE REVIEW

**Comment by LordEidi** [comment]
Oh thanks! Very much looking forward to merging these changes.

Although I am thinking about configuring LDAP as an optional module. I don't like the idea that everybody will have to install the LDAP module when it is not used.

Any ideas how to solve that?

**Comment by nebulade** [comment]
I guess the only option is to document that if ldap is configure one also has to manually run 
```
npm install ldapjs
```
in the project folder?

**Comment by LordEidi** [comment]
I've read some strategies to lazy load the module and things like that. Ah well, I will probably just add a line to the readme :/

**Comment by nebulade** [comment]
The code now requires ldapjs on demand. Does that look better?

**Comment by LordEidi** [comment]
Just an update. Did not forget about you. I am just a bit busy atm, will try to merge the changes in the next few days.

**Comment by nebulade** [comment]
Thanks for the heads up

**Comment by LordEidi** [comment]
Added your changes. Had some problems merging...

Again, many thanks!

**Comment by nebulade** [comment]
Great thanks! I am then closing this merge request. I will then attempt to build a fennel Cloudron app.

**Pull request closed without merging**
